version: "3"

services:
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./api/MongoDB:/data/db
    networks:
      - swarm_overlay3
    logging:
      driver: none
  mosquitto:
    logging:
      driver: none    
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - swarm_overlay3
  rest-api:
    hostname: rest-api
    container_name: rest-api
    depends_on: ["mongo"]
    build: ./api
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/usr/app
    networks:
      - swarm_overlay3
    healthcheck:
        test: ["CMD", "curl", "-f", "http://mongo:27017"]
        interval: 30s
        timeout: 10s
        retries: 5           
  web-app:
    hostname: web-app
    container_name: web-app
    depends_on: ["rest-api"]
    logging:
      driver: none
    build: ./web-app
    ports:
      - "8081:80"
    networks:
      - swarm_overlay3
networks: 
  swarm_overlay3:
      driver: overlay
      external: true