version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./MongoDB:/data/db
    networks:
      - express-mongo-network
    logging:
      driver: none      
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    # volumes:
    #   - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - express-mongo-network
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - express-mongo-network
    healthcheck:
        test: ["CMD", "curl", "-f", "http://mongo:27017"]
        interval: 30s
        timeout: 10s
        retries: 5            
networks: 
    express-mongo-network:
      driver: bridge      